name: Generate Report and Send Email

on:
  push:
    branches:
      - main

jobs:
  generate_report:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Reports Directory
        run: |
          if (-not (Test-Path -Path reports)) {
            New-Item -ItemType Directory -Path reports
          }

      - name: Generate Report
        run: |
          # Replace with your report generation command
          echo "Report generated on $(Get-Date)" > reports/report.txt

      - name: Compress Report
        run: |
          Compress-Archive -Path reports\* -DestinationPath reports.zip

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: reports.zip

  send_email:
    runs-on: ubuntu-latest
    needs: generate_report
    if: always()

    steps:
      - name: Download Report Artifact
        uses: actions/download-artifact@v2
        with:
          name: report

      - name: Send Email with Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Report from GitHub Actions
          to: aayush.batra@simplefixit.com
          from: GitHub Actions <${{ secrets.MAIL_USERNAME }}>
          body: Please find the attached report generated by the GitHub Actions workflow.
          attachments: reports.zip
