name: Scheduled Selenium Tests

on:
  schedule:
    # Run at 09:30 UTC (3:00 PM IST) Monday–Friday
    - cron: '30 9 * * 1-5'
  workflow_dispatch:

jobs:
  test_and_generate_report:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest and generate HTML report
        run: |
          if (!(Test-Path reports)) { New-Item -ItemType Directory -Path reports }
          pytest --html=reports/report.html --self-contained-html
        shell: pwsh

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: reports/report.html

      - name: Send test report via email (using mirromutth/email)
        uses: mirromutth/email@v1
        with:
          server_address: smtp.gmail.com                     # Replace if using Outlook or SendGrid
          server_port: 465
          secure: true                                       # SSL (true) or TLS (false for port 587)
          username: ${{ secrets.EMAIL_USERNAME }}           # Full email (e.g. you@gmail.com)
          password: ${{ secrets.EMAIL_PASSWORD }}           # App password (no spaces)
          subject: Selenium Test Report
          to: shubhamkohli2002@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hi,

            Please find the attached Selenium test report from the scheduled run.

            Regards,  
            GitHub Actions
          attachments: reports/report.html
